//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebForm.MonitoringRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MonitoringRef.IMonitoringService")]
    public interface IMonitoringService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMonitoringService/numberOfRequest", ReplyAction="http://tempuri.org/IMonitoringService/numberOfRequestResponse")]
        int numberOfRequest(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMonitoringService/numberOfRequest", ReplyAction="http://tempuri.org/IMonitoringService/numberOfRequestResponse")]
        System.Threading.Tasks.Task<int> numberOfRequestAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMonitoringService/avgTimeRequest", ReplyAction="http://tempuri.org/IMonitoringService/avgTimeRequestResponse")]
        int avgTimeRequest(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMonitoringService/avgTimeRequest", ReplyAction="http://tempuri.org/IMonitoringService/avgTimeRequestResponse")]
        System.Threading.Tasks.Task<int> avgTimeRequestAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMonitoringService/cityPopularity", ReplyAction="http://tempuri.org/IMonitoringService/cityPopularityResponse")]
        int cityPopularity(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMonitoringService/cityPopularity", ReplyAction="http://tempuri.org/IMonitoringService/cityPopularityResponse")]
        System.Threading.Tasks.Task<int> cityPopularityAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMonitoringService/mostPopularCity", ReplyAction="http://tempuri.org/IMonitoringService/mostPopularCityResponse")]
        string mostPopularCity();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMonitoringService/mostPopularCity", ReplyAction="http://tempuri.org/IMonitoringService/mostPopularCityResponse")]
        System.Threading.Tasks.Task<string> mostPopularCityAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMonitoringService/cities", ReplyAction="http://tempuri.org/IMonitoringService/citiesResponse")]
        System.Collections.Generic.Dictionary<string, int> cities();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMonitoringService/cities", ReplyAction="http://tempuri.org/IMonitoringService/citiesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, int>> citiesAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMonitoringServiceChannel : WebForm.MonitoringRef.IMonitoringService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MonitoringServiceClient : System.ServiceModel.ClientBase<WebForm.MonitoringRef.IMonitoringService>, WebForm.MonitoringRef.IMonitoringService {
        
        public MonitoringServiceClient() {
        }
        
        public MonitoringServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MonitoringServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MonitoringServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MonitoringServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int numberOfRequest(string name) {
            return base.Channel.numberOfRequest(name);
        }
        
        public System.Threading.Tasks.Task<int> numberOfRequestAsync(string name) {
            return base.Channel.numberOfRequestAsync(name);
        }
        
        public int avgTimeRequest(string name) {
            return base.Channel.avgTimeRequest(name);
        }
        
        public System.Threading.Tasks.Task<int> avgTimeRequestAsync(string name) {
            return base.Channel.avgTimeRequestAsync(name);
        }
        
        public int cityPopularity(string name) {
            return base.Channel.cityPopularity(name);
        }
        
        public System.Threading.Tasks.Task<int> cityPopularityAsync(string name) {
            return base.Channel.cityPopularityAsync(name);
        }
        
        public string mostPopularCity() {
            return base.Channel.mostPopularCity();
        }
        
        public System.Threading.Tasks.Task<string> mostPopularCityAsync() {
            return base.Channel.mostPopularCityAsync();
        }
        
        public System.Collections.Generic.Dictionary<string, int> cities() {
            return base.Channel.cities();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, int>> citiesAsync() {
            return base.Channel.citiesAsync();
        }
    }
}
